### ISSUE TITLE
Unable to add Azure with InsightCloudSec

### ISSUE THREAD

**Issue by sumeshsquare** [gstotts/terraform-provider-insightcloudsec#55]
Getting the error when trying to add InsightCloudSec with Azure, Kindly assist

![Screenshot 2022-06-21](https://user-images.githubusercontent.com/36350499/174792931-6db96f3b-5977-4c5d-93d7-3cc59fe49592.jpg)

**Comment by gstotts** [comment]
I will try and devote some time to looking at this.  It may be an issue with the API client .. there were some changes made awhile ago that may be related.  I'll spin up a test subscription and see what I can find.  If you set your debug logging (set environment variable TF_LOG=DEBUG) that may provide some additional help in troubleshooting.

**Comment by gstotts** [comment]
Please update the provider to version 0.3.1 and try running again.

**Comment by gstotts** [comment]
I tested this evening and was able to successfully have my azure account created.  I used a resource block like this:
```hcl
resource "insightcloudsec_cloud" "my_azure_cloud" {
    name            = "Stotts Azure Cloud"
    cloud_type      = "AZURE_ARM"
    tenant_id       = ""
    subscription_id = ""
    app_id          = ""
    api_key         = ""
}
```
With valid IDs and API-Key, the above created without issue.


1.  Can you verify the version you are using?

2.  Can you set an environment variable for TF_LOG to debug (i.e. `export TF_LOG=DEBUG`), the the apply, and provide the output (minus any identifiers or sensitive ids/keys)?
